# config.yaml
train:
  batch_size: 32
  max_epochs: 10
  learning_rate: 0.01
  seed: 42

logging:
  project_name: "xai-project"
  log_model: "all"
  local_dirpath: "./checkpoints"

data:
  num_classes: 60
  transform:
    resize: [256, 256]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
